### ISSUE TITLE
Erro na busca por palavra-chave no branch dev

### ISSUE THREAD

**Issue by leogregianin** [hugodias/san-pedro-valley-jobs#74]
Estou testando o branch "dev" do site e está me retornando um erro quando pesquisa por palavra-chave no search do app/models/job.rb.

A única diferença é a versão do ruby local 2.3.3 e o elasticsearch está iniciado. 

gemfile:
```
ruby "2.3.3"
gem "rails", "4.2.5.2"
gem "searchkick", "~> 1.2.1"
```

Erro:
`Searchkick::InvalidQueryError at /
[400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22}],"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22},"status":400}`

Imagem da tela: [aqui](https://www.dropbox.com/s/gjedbqsnpsdv20c/Captura%20de%20tela%202017-07-28%2019.19.11.png?dl=0)

**Comment by Hamdan85** [comment]
leo, atualiza sua versão do searchkick... ja rolou isso comigo antes...
